menu:
    Blog: /
    GitHub: https://github.com/twinkletwinklelittlestar70
    Archive: archives/

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: claymcleod 
disqus: true

# Analytics
# ga: UA-xxxxxxxx-x
ga: UA-210509391-1

# Copyright Infomation
startyear: 2019

# Image Credits
enable_image_credit: true 
